### ISSUE TITLE
Classifiers proposal

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-classifiers#3]
# Classifiers for oSPARC-based Data-Items

Document to propose classifiers for the annotation of oSPARC-based Data-Items. Related to the [K-CORE/SIM-CORE curation discussions document](https://docs.google.com/document/d/1liIUnFopSaeMSjPRV2EvIJnSfpMeT1En_AKls47wtPc/edit?usp=sharing).

# 📁 Type of study

*   Data analysis
*   Data processing
*   Visualization
*   Simulation study
*   Guided mode available
*   Published _(on the Portal)_

# 📁 Type of service

*   Computational
*   Interactive
*   (Script) Runner
*   Viewer
*   Controllable
*   Jupyter Notebook [SCR_018315](https://scicrunch.org/resources/Any/record/nlx_144509-1/SCR_018315/resolver?q=Jupyter&l=Jupyter)
*   Anatomical Phantom
*   📁 Programming language
    *   Python [SCR_008394](https://scicrunch.org/resources/Any/record/nlx_144509-1/SCR_008394/resolver?q=SCR_008394&l=SCR_008394)
    *   Octave [SCR_014398](https://scicrunch.org/resources/Any/record/nlx_144509-1/SCR_014398/resolver?q=Octave&l=Octave)
    *   OpenCL
    *   C/C++
    *   JavaScript

# 📁 Study content:

*   Neuromodulation 
*   Neural interface
*   Organ physiology
*   Control
*   Optimization
*   Sensitivity/Uncertainty Analysis
*   ML/AI
*   Image-based modeling
*   Anatomy-based modeling
*   Mechanistic Model
*   Data-driven Model
*   Multi-scale
*   Tissue model
*   Neural sensing
*   In silico trial
*   Treatment planning
*   Personalized modeling

**Comment by pcrespov** [comment]
@esraneufeld I think ``computational`` and ``interactive`` are implicit in the service so the system already knows that. Therefore, they should not be classifiers. IMO, classifiers should be *static* tags **explicitly** assigned by the user that enhances what the system already knows about the service/study. Same with ``Runner``, ``Viewer``, ``Controllable`` and ``Jupyter``

**Comment by esraneufeld** [comment]
@pcrespov  that make sense. i only put it there, because i thought that people might want to filter for it. but of course, we can always enable that by directly filtering the meta-data.
